### ISSUE TITLE
[suggestion] index.glsl

### ISSUE THREAD

**Issue by mattdesl** [superguigui/color-shader-functions#1]
If you use `index.glsl` as the filename inside a folder, the following should resolve correctly:

``` glsl
#pragma glslify: sepia = require('color-shader-functions/sepia')
```

Leads to shorter requires. :smile:

**Comment by superguigui** [comment]
That's much better indeed thanks :D 
I pushed new filenames with updated readme.

**Comment by mattdesl** [comment]
Also; maybe `glsl-*` prefix would be more in line with other glslify components?

``` glsl
#pragma glslify: sepia = require('glsl-color-functions/sepia')
```

**Comment by mattdesl** [comment]
Ah just realized it's already on npm. :smile: no biggie

**Comment by superguigui** [comment]
Yeah renaming on NPM seems a little annoying... I don't see any way beside [this](https://docs.npmjs.com/cli/deprecate). 
I don't know if it's good to have all these functions in one module anyway. It would be better to separate them, but at the time I felt guilty making a bunch of modules for short methods i gathered here and there :smile:.

**Comment by mattdesl** [comment]
I think it's OK to have them all in a single repo since they are very opinionated and app-specific (i.e. sepia has all sorts of magic numbers). :smile:
